export const INTERMEDIATE_CURRENCY = 'BTC';

export const AGGREGATE_INDEX_TYPE = '5';
export const EXCHANGE_INDEX = 'CCCAGG';

export const SUBSCRIBECOMPLETE_MESSAGE = 'SUBSCRIBECOMPLETE';
export const SUBSCRIPTION_UNRECOGNIZED_MESSAGE = 'SUBSCRIPTION_UNRECOGNIZED';
export const SUBSCRIPTION_ALREADY_ACTIVE_MESSAGE = 'SUBSCRIPTION_ALREADY_ACTIVE';

export const UNSUBSCRIBECOMPLETE_MESSAGE = 'UNSUBSCRIBECOMPLETE';
export const INVALID_SUB_MESSAGE = 'INVALID_SUB';
